### ISSUE TITLE
Is the setTempo interface showing the correct property name ?

### ISSUE THREAD

**Issue by stephaneeybert** [chrisguttandin/midi-json-parser-worker#329]
When using the [interface](https://github.com/chrisguttandin/midi-json-parser-worker/blob/master/src/interfaces/midi-set-tempo-event.ts) I'm surprised by the property name as I expected it to be per quarter and not per beat.

Having just read the MIDI documentation I was expecting:
```
setTempo: {
  microsecondsPerQuarter: number;
};
```
instead of:
```
setTempo: {
  microsecondsPerBeat: number;
};

```

**Comment by chrisguttandin** [comment]
Hi Stephane,

I'm not sure. I always thought of a beat and a quarter note as synonyms. Do you have an example file where this is not the case?

**Comment by stephaneeybert** [comment]
Hi Chris,
Thanks for your very prompt response. I am a newbie in music theory and notation so I'm quite careful in my wording when I say something on the subject.
I reckon the quarter note is one beat if the time signature denominator is 4 but if it's different than 4 then a quarter note is not any longer one beat as seen in the [example 20](https://www.uwsuper.edu/acaddept/music/courses/musictheory/upload/PreTheory-Lesson-5.pdf).

**Comment by chrisguttandin** [comment]
Yes, you're right. The time signature event allows to change the numerator and then a quarter is not necessarily a beat anymore.

Do you want to submit a PR to change `microsecondsPerBeat` to `microsecondsPerQuarter` as you suggested?

**Comment by stephaneeybert** [comment]
Sure ! I understand the correction is only about renaming the property. I could not touch at the API internals for fear of breaking something, my knowledge of music theory being so limited.

**Comment by chrisguttandin** [comment]
Thanks again for fixing this. #330 is merged and v8 is published on npm. I will continue to update packages which depend on this.

**Comment by stephaneeybert** [comment]
Glad I could help ! I shall update my dependency now.
