### ISSUE TITLE
Support MIDI Cue Point meta message

### ISSUE THREAD

**Issue by infojunkie** [chrisguttandin/midi-json-parser-worker#337]
I am generating [Cue Point meta messages](https://www.recordingblogs.com/wiki/midi-cue-point-meta-message) in my MIDI file to synchronize the music sheet with the playback. It would be great if your module supported them :pray:

**Comment by infojunkie** [comment]
Note, I can also use a Marker meta message, but for completeness sake, supporting cue points is still valuable imo :-)

**Comment by chrisguttandin** [comment]
Thanks for pointing this out. I more or less only implemented what I found in existing MIDI files so far. Do you maybe have an example file which contains such a message which could be used as a fixture as part of this repo?

**Comment by infojunkie** [comment]
Sure, [here's one](https://github.com/chrisguttandin/midi-json-parser-worker/files/8317981/26-2.zip). Thanks!

**Comment by chrisguttandin** [comment]
Thanks a lot. The update has been published as v8.1 of midi-json-parser-worker and [midi-json-parser](https://github.com/chrisguttandin/midi-json-parser) respectively. I will also update [json-midi-encoder](https://github.com/chrisguttandin/json-midi-encoder) to support the encoding of cue point events.
